[all]
k8s-worker-2 ansible_host=box-snt5a83d-dnjnfdho.meshnet.local
k8s-master-1 ansible_host=box-snt5a83d-05qwnnyj.meshnet.local
k8s-worker-1 ansible_host=box-snt5a83d-jptnjdvz.meshnet.local

[all:vars]
ansible_user=easyenv
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

# Kubernetes Cluster Groups
[kube_master]
k8s-master-1

[kube_workers]
k8s-worker-2
k8s-worker-1

[kubernetes:children]
kube_master
kube_workers
